# Generated by Django 4.2.30 on 2026-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Tên đăng nhập')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Mật khẩu')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ tên')),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Avatar URL')),
                ('role', models.CharField(choices=[('admin', 'Quản trị viên'), ('user', 'Người dùng')], default='user', max_length=20, verbose_name='Vai trò')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Lần đăng nhập cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
