# Generated by Django 4.2.30 on 2026-05-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models_ai', '0001_initial'),
        ('datasets', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('preparing', 'Đang chuẩn bị'), ('training', 'Đang huấn luyện'), ('validating', 'Đang kiểm tra'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('status_message', models.TextField(blank=True, null=True, verbose_name='Thông báo trạng thái')),
                ('epochs', models.IntegerField(default=10, verbose_name='Số epoch')),
                ('batch_size', models.IntegerField(default=16, verbose_name='Batch size')),
                ('learning_rate', models.FloatField(default=0.001, verbose_name='Learning rate')),
                ('optimizer', models.CharField(default='adam', max_length=50, verbose_name='Optimizer')),
                ('loss_function', models.CharField(default='categorical_crossentropy', max_length=100, verbose_name='Loss function')),
                ('train_accuracy', models.FloatField(blank=True, null=True, verbose_name='Train accuracy')),
                ('validation_accuracy', models.FloatField(blank=True, null=True, verbose_name='Val accuracy')),
                ('train_loss', models.FloatField(blank=True, null=True, verbose_name='Train loss')),
                ('validation_loss', models.FloatField(blank=True, null=True, verbose_name='Val loss')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Thời gian (s)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('dataset', models.ForeignKey(db_column='dataset_id', on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='datasets.dataset', verbose_name='Bộ dữ liệu')),
                ('model', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='models_ai.cnnmodel', verbose_name='Mô hình')),
                ('trained_by', models.ForeignKey(db_column='trained_by', on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='authentication.user', verbose_name='Người huấn luyện')),
            ],
            options={
                'verbose_name': 'Job huấn luyện',
                'verbose_name_plural': 'Job huấn luyện',
                'db_table': 'training_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch_number', models.IntegerField(verbose_name='Epoch')),
                ('train_accuracy', models.FloatField(blank=True, null=True, verbose_name='Train accuracy')),
                ('validation_accuracy', models.FloatField(blank=True, null=True, verbose_name='Val accuracy')),
                ('train_loss', models.FloatField(blank=True, null=True, verbose_name='Train loss')),
                ('validation_loss', models.FloatField(blank=True, null=True, verbose_name='Val loss')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('training_job', models.ForeignKey(db_column='training_job_id', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='training.trainingjob', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Lịch sử epoch',
                'verbose_name_plural': 'Lịch sử epoch',
                'db_table': 'training_history',
                'ordering': ['epoch_number'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Accuracy')),
                ('precision_score', models.FloatField(blank=True, null=True, verbose_name='Precision')),
                ('recall_score', models.FloatField(blank=True, null=True, verbose_name='Recall')),
                ('f1_score', models.FloatField(blank=True, null=True, verbose_name='F1 score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('training_job', models.ForeignKey(db_column='training_job_id', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='training.trainingjob', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Metrics mô hình',
                'verbose_name_plural': 'Metrics mô hình',
                'db_table': 'model_metrics',
            },
        ),
    ]
