# Generated by Django 4.2.30 on 2026-05-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CnnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Tên mô hình')),
                ('model_slug', models.CharField(max_length=100, unique=True, verbose_name='Slug')),
                ('architecture_type', models.CharField(default='cnn_basic', max_length=100, verbose_name='Kiến trúc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('framework', models.CharField(default='tensorflow', max_length=50, verbose_name='Framework')),
                ('input_width', models.IntegerField(default=128, verbose_name='Chiều rộng input')),
                ('input_height', models.IntegerField(default=128, verbose_name='Chiều cao input')),
                ('channels', models.IntegerField(default=3, verbose_name='Kênh màu')),
                ('total_parameters', models.BigIntegerField(blank=True, null=True, verbose_name='Số tham số')),
                ('model_file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn file')),
                ('model_size_mb', models.FloatField(blank=True, null=True, verbose_name='Dung lượng MB')),
                ('version', models.CharField(default='1.0.0', max_length=50, verbose_name='Phiên bản')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='cnn_models', to='authentication.user', verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Mô hình CNN',
                'verbose_name_plural': 'Mô hình CNN',
                'db_table': 'cnn_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
