# Generated by Django 4.2.30 on 2026-05-25 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100, verbose_name='Tên phiên bản')),
                ('version_number', models.CharField(max_length=50, verbose_name='Số phiên bản')),
                ('model_path', models.CharField(max_length=500, verbose_name='Đường dẫn file')),
                ('accuracy_score', models.FloatField(blank=True, null=True, verbose_name='Độ chính xác')),
                ('is_production', models.BooleanField(default=False, verbose_name='Đang dùng production')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('model', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='models_ai.cnnmodel', verbose_name='Mô hình')),
            ],
            options={
                'verbose_name': 'Phiên bản mô hình',
                'verbose_name_plural': 'Phiên bản mô hình',
                'db_table': 'model_versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
